### ISSUE TITLE
Issue On Migration

### ISSUE THREAD

**Issue by sanjay0130** [shakthisachintha/Group-Project#10]
Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `group-project`.`attendances` (errno: 150 "Foreign key constraint is incorrectly formed")")
      E:\xampp\htdocs\crm-projects\Group-Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

  2   PDOStatement::execute()
      E:\xampp\htdocs\crm-projects\Group-Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

**Comment by shakthisachintha** [comment]
Some MySQL versions produce theses errors, you can try wamp server latest version sure it will fix the issues with the migrations.

**Comment by ubongofaidas** [comment]
> 
> 
> Exception trace:
> 
> 1 PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `group-project`.`attendances` (errno: 150 "Foreign key constraint is incorrectly formed")")
> E:\xampp\htdocs\crm-projects\Group-Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458
> 
> 2 PDOStatement::execute()
> E:\xampp\htdocs\crm-projects\Group-Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

even me I'm getting this error on  migration

**Comment by em-torres** [comment]
I made a PR about this issue: https://github.com/shakthisachintha/Group-Project/pull/15

Main problem was in some fields with the ForeignKeys which had to be ```unsigned```

**Comment by systimanx-itsol** [comment]
issue on migration::: Migrating: 2019_09_07_050834_create_attendances_table

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'attendances_user_id_foreign' are incompatible. (SQL: alter table `attendances` add constraint `attendances_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)

  at /var/www/html/hms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'attendances_user_id_foreign' are incompatible.")
      /var/www/html/hms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /var/www/html/hms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  Please use the argument -v to see more details.

**Comment by zafrantsany** [comment]
> issue on migration::: Migrating: 2019_09_07_050834_create_attendances_table
> 
> Illuminate\Database\QueryException : SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'attendances_user_id_foreign' are incompatible. (SQL: alter table `attendances` add constraint `attendances_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)
> 
> at /var/www/html/hms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
> 660| // If an exception occurs when attempting to run a query, we'll format the error
> 661| // message to include the bindings with SQL, which will make this exception a
> 662| // lot more helpful to the developer instead of just the database's errors.
> 663| catch (Exception $e) {
> 
> > 664|             throw new QueryException(
> > 665|                 $query, $this->prepareBindings($bindings), $e
> > 666|             );
> > 667|         }
> > 668|
> 
> Exception trace:
> 
> 1 PDOException::("SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'attendances_user_id_foreign' are incompatible.")
> /var/www/html/hms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458
> 
> 2 PDOStatement::execute()
> /var/www/html/hms/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458
> 
> Please use the argument -v to see more details.

Change this code from this :
$table->bigInteger('user_id');

to this :
$table->unsignedBigInteger('user_id')->nullable();

It works for me..

**Comment by shakthisachintha** [comment]
Issue is now resolved
