### ISSUE TITLE
php artisan migrate failed

### ISSUE THREAD

**Issue by mworia-Br** [shakthisachintha/Group-Project#27]
`Migrating: 2019_09_07_050834_create_attendances_table

   Illuminate\Database\QueryException  : SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "KEY"
LINE 1: ALTER TABLE attendances ADD UNIQUE KEY(`user_id`,`start`)
                                           ^ (SQL: ALTER TABLE attendances ADD UNIQUE KEY(`user_id`,`start`))

  at C:\xampp\htdocs\Group-Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "KEY"
LINE 1: ALTER TABLE attendances ADD UNIQUE KEY(`user_id`,`start`)
                                           ^")
      C:\xampp\htdocs\Group-Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:507

  2   PDO::exec("ALTER TABLE attendances ADD UNIQUE KEY(`user_id`,`start`)")
      C:\xampp\htdocs\Group-Project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:507

  Please use the argument -v to see more details.

user@DESKTOP-C04DP0N MINGW64 /c/xampp/htdocs/Group-Project`

**Comment by AlexVish85** [comment]
+1
**Error in every migrating table!**
When a migration occurs, in each created table, an error pops up in the terminal

**Comment by sonumusa** [comment]
in migration file make change biginteger to unsignedBigInteger. migration succesfull
